"use client";
import { useMemo, useState } from "react";
import { Camera, CheckCircle2, Eye, EyeOff } from "lucide-react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/providers/AuthProvider";
import { ThemePicker } from "@/components/providers/ThemeProvider";
import { useXaadirData } from "@/components/providers";
import { InitialAvatar, PageHeader, PrimaryButton, SecondaryButton } from "./AdminUI";
import { processProfileImage } from "@/lib/profile-image";
import { useDialog } from "@/components/layout/useDialog";
import styles from "./admin.module.css";
const tabs = ["Profile", "Account", "Security", "School", "Attendance", "Academic Calendar", "Branding", "Preferences"];

export function AdminSettings() {
  const router = useRouter(); const { state, updateAdminProfile, updateAdminAccount, updateSchool } = useXaadirData(); const { signOut, session } = useAuth();
  const [tab, setTab] = useState("Profile"); const [name, setName] = useState(state.adminProfile.fullName); const [contactEmail, setContactEmail] = useState(state.adminProfile.contactEmail ?? state.adminProfile.email); const [phone, setPhone] = useState(state.adminProfile.phone ?? ""); const [image, setImage] = useState(state.adminProfile.profileImage); const [loginEmail, setLoginEmail] = useState(state.adminProfile.email); const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false); const [passwordOpen, setPasswordOpen] = useState(false);
  const dirty = useMemo(() => name !== state.adminProfile.fullName || contactEmail !== (state.adminProfile.contactEmail ?? state.adminProfile.email) || phone !== (state.adminProfile.phone ?? "") || image !== state.adminProfile.profileImage, [name, contactEmail, phone, image, state.adminProfile]);
  const feedback = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(""), 1800); };
  async function saveProfile() { setSaving(true); const result = updateAdminProfile({ fullName: name, contactEmail, phone, profileImage: image }); setSaving(false); feedback(result.ok ? "Profile saved" : "Profile could not be saved"); }
  function logout() { signOut(); router.replace("/login"); }
  return <div className={styles.page}><PageHeader title="Settings" subtitle="Manage your administrator profile and account." /><div className={styles.settingsLayout}><nav className={styles.settingsNav} aria-label="Settings sections">{tabs.map(item => <button key={item} className={tab === item ? styles.settingsActive : ""} onClick={() => setTab(item)}>{item}</button>)}</nav><section className={`${styles.settingsPanel} ${styles.settingsContent}`}><h2>{tab}</h2>
    {tab === "Profile" && <><div className={styles.settingsAvatar}><InitialAvatar name={name} image={image} large /><div><label className={styles.secondaryButton}><Camera />{image ? "Replace Picture" : "Upload Picture"}<input hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={async event => { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; try { setImage(await processProfileImage(file)); } catch (error) { feedback(error instanceof Error ? error.message : "Image could not be processed"); } }} /></label>{image && <SecondaryButton onClick={() => setImage(undefined)}>Remove</SecondaryButton>}<small>PNG, JPG or WEBP · Max 2 MB</small></div></div><Field label="Full Name" value={name} onChange={setName} /><Field label="Contact Email" type="email" value={contactEmail} onChange={setContactEmail} /><Field label="Phone" type="tel" value={phone} onChange={setPhone} /><p>Role: Administrator</p>{dirty && <small className={styles.unsaved}>Unsaved changes</small>}<div className={styles.settingsActions}><PrimaryButton disabled={!dirty || saving} onClick={saveProfile}>{saving ? "Saving…" : notice === "Profile saved" ? "✓ Saved" : "Save Profile"}</PrimaryButton></div></>}
    {tab === "Account" && <><div className={styles.accountSummary}><span>Login Email</span><strong>{state.adminProfile.email}</strong><span>Account Type</span><strong>Administrator</strong><span>Account Status</span><strong>Active</strong></div><Field label="Change Login Email" type="email" value={loginEmail} onChange={setLoginEmail} /><PrimaryButton disabled={loginEmail === state.adminProfile.email} onClick={() => { const result = updateAdminAccount({ email: loginEmail }); feedback(result.ok ? "Login email saved" : result.error); }}>Save Login Email</PrimaryButton><SecondaryButton onClick={() => setPasswordOpen(true)}>Change Password</SecondaryButton><SecondaryButton onClick={logout}>Logout</SecondaryButton></>}
    {tab === "Security" && <><p>Password</p><SecondaryButton onClick={() => setPasswordOpen(true)}>Change Password</SecondaryButton><p>Current session active</p><SecondaryButton onClick={logout}>Sign out of Xaadir</SecondaryButton></>}
    {tab === "School" && <><p>School identity settings remain available here.</p><Field label="School Name" value={state.school.name} onChange={value => updateSchool({ name: value })} /></>}
    {tab === "Preferences" && <ThemePicker />}
    {!["Profile", "Account", "Security", "School", "Preferences"].includes(tab) && <p>{tab} configuration is available in the existing school settings.</p>}{notice && <span className={styles.notice}><CheckCircle2 />{notice}</span>}</section></div>{passwordOpen && <PasswordModal onClose={() => setPasswordOpen(false)} onSaved={feedback} update={updateAdminAccount} currentEmail={session?.email ?? state.adminProfile.email} />}</div>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label className={styles.field}><span>{label}</span><input type={type} value={value} onChange={event => onChange(event.target.value)} /></label>; }
function PasswordModal({ onClose, onSaved, update, currentEmail }: { onClose: () => void; onSaved: (message: string) => void; update: (input: { password: string; currentPassword: string }) => { ok: boolean; error?: string }; currentEmail: string }) { const dialog = useDialog(true, onClose); const [current, setCurrent] = useState(""); const [next, setNext] = useState(""); const [confirm, setConfirm] = useState(""); const [show, setShow] = useState(false); return <div className={`${styles.overlay} ${styles.centeredOverlay}`} role="presentation"><section ref={dialog} tabIndex={-1} className={`${styles.confirmDialog} ${styles.passwordDialog}`} role="dialog" aria-modal="true" aria-label="Change Password"><h2>Change Password</h2><p>Update the password for {currentEmail}.</p><input type={show ? "text" : "password"} aria-label="Current password" autoComplete="current-password" placeholder="Current password" value={current} onChange={event => setCurrent(event.target.value)} /><input type={show ? "text" : "password"} aria-label="New password" autoComplete="new-password" placeholder="New password" value={next} onChange={event => setNext(event.target.value)} /><input type={show ? "text" : "password"} aria-label="Confirm new password" autoComplete="new-password" placeholder="Confirm new password" value={confirm} onChange={event => setConfirm(event.target.value)} /><button type="button" onClick={() => setShow(!show)}>{show ? <EyeOff /> : <Eye />} {show ? "Hide" : "Show"}</button><div><SecondaryButton onClick={onClose}>Cancel</SecondaryButton><PrimaryButton onClick={() => { if (next.length < 8 || next !== confirm) { onSaved("Use a matching password of at least 8 characters"); return; } const result = update({ password: next, currentPassword: current }); if (result.ok) { onClose(); onSaved("Password changed"); } else onSaved(result.error ?? "Password could not be changed"); }}>Change Password</PrimaryButton></div></section></div>; }
