"use client";
import { useMemo, useState } from "react";
import { AlertTriangle, BarChart3, CalendarCheck2, Download, Filter, Send, Users } from "lucide-react";
import { useXaadirData } from "@/components/providers";
import { analyticsDates, buildAnalytics, type AnalyticsRange } from "@/lib/analytics";
import { PageHeader, PrimaryButton, SelectField, styles } from "./AdminUI";
import { useDialog } from "@/components/layout/useDialog";
import analyticsStyles from "./analytics.module.css";

const pct = (value: number | null) => value === null ? "—" : `${value.toFixed(1)}%`;
export function AnalyticsWorkspace() {
  const { state, sendMessage } = useXaadirData();
  const [range, setRange] = useState<AnalyticsRange>("MONTH");
  const [classId, setClassId] = useState("ALL"); const [teacherId, setTeacherId] = useState("ALL"); const [subjectId, setSubjectId] = useState("ALL"); const [selectedClass, setSelectedClass] = useState<string | null>(null); const [sent, setSent] = useState("");
  const dates = useMemo(() => analyticsDates(range), [range]);
  const data = useMemo(() => buildAnalytics(state, dates, classId, teacherId, subjectId), [state, dates, classId, teacherId, subjectId]);
  const max = Math.max(...data.trend.map(item => item.rate ?? 0), 1);
  function messageTeacher(targetTeacherId: string, attachment: Parameters<typeof sendMessage>[0]["attachment"], body: string) {
    const teacher = state.teachers.find(item => item.id === targetTeacherId); const account = state.accounts.find(item => item.teacherId === targetTeacherId && item.status === "ACTIVE");
    if (!teacher || !account) return;
    sendMessage({ recipientUserId: account.id, recipientName: teacher.fullName, body, attachment }); setSent(attachment?.entityId ?? targetTeacherId); window.setTimeout(() => setSent(""), 1600);
  }
  function assignmentForClass(targetClassId: string) { return state.assignments.find(item => item.classId === targetClassId); }
  return <div className={styles.page}><PageHeader title="Analytics" subtitle="Understand attendance, class performance and school activity." actions={<PrimaryButton><Download /> Export</PrimaryButton>} />
    <section className={analyticsStyles.filters}><div><Filter /><strong>Filters</strong></div><SelectField label="Date range" value={range} onChange={value => setRange(value as AnalyticsRange)}><option value="TODAY">Today</option><option value="WEEK">This Week</option><option value="MONTH">This Month</option><option value="LAST_MONTH">Last Month</option></SelectField><SelectField label="Class" value={classId} onChange={setClassId}><option value="ALL">All Classes</option>{state.classes.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><SelectField label="Teacher" value={teacherId} onChange={setTeacherId}><option value="ALL">All Teachers</option>{state.teachers.map(item => <option key={item.id} value={item.id}>{item.fullName}</option>)}</SelectField><SelectField label="Subject" value={subjectId} onChange={setSubjectId}><option value="ALL">All Subjects</option>{state.subjects.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectField></section>
    <section className={analyticsStyles.metrics}><Metric label="Overall attendance" value={pct(data.rate)} note={data.eligible ? `${data.attended} attended records` : "No submitted registers"} icon={<BarChart3 />} /><Metric label="Students present" value={data.counts.PRESENT} note={`${data.eligible} submitted records`} icon={<Users />} /><Metric label="Absent today" value={data.counts.ABSENT} note="From submitted registers" icon={<AlertTriangle />} /><Metric label="Registers completed" value={`${data.sessions.length} / ${data.expected}`} note={`${Math.max(0, data.expected - data.sessions.length)} not submitted`} icon={<CalendarCheck2 />} /></section>
    <div className={analyticsStyles.grid}><section className={`${analyticsStyles.panel} ${analyticsStyles.trend}`}><div className={analyticsStyles.heading}><div><span>Attendance trend</span><small>Instructional dates only · submitted records only</small></div></div>{data.trend.some(item => item.rate !== null) ? <div className={analyticsStyles.chartScroll} tabIndex={0} role="region" aria-label="Attendance trend, scroll for all dates"><div className={analyticsStyles.chart} style={{ minWidth: `${data.trend.length * 40}px` }} aria-label="Attendance trend">{data.trend.map(point => <div className={analyticsStyles.bar} key={point.date} title={`${point.date}: ${pct(point.rate)}`} style={{ height: `${Math.max(8, (point.rate ?? 0) / max * 100)}%` }}><strong>{pct(point.rate)}</strong><small>{new Date(`${point.date}T12:00:00`).toLocaleDateString("en-GB", { weekday: "short" })}</small></div>)}</div></div> : <Empty />}</section>
      <section className={analyticsStyles.panel}><div className={analyticsStyles.heading}><span>Status breakdown</span></div><div className={analyticsStyles.breakdown}>{(["PRESENT", "ABSENT", "LATE", "EXCUSED"] as const).map(status => <div key={status}><span>{status[0] + status.slice(1).toLowerCase()}</span><strong>{data.eligible ? `${(data.counts[status] / data.eligible * 100).toFixed(1)}%` : "—"}</strong><i style={{ width: `${data.eligible ? data.counts[status] / data.eligible * 100 : 0}%` }} data-status={status} /></div>)}</div></section>
      <section className={`${analyticsStyles.panel} ${analyticsStyles.wide}`}><div className={analyticsStyles.heading}><div><span>Class attendance</span><small>Click a class for a read-only drilldown.</small></div></div><table className={analyticsStyles.table}><thead><tr><th>Class</th><th>Students</th><th>Attendance</th><th>Registers</th><th>Action</th></tr></thead><tbody>{data.classStats.map(item => { const assignment = assignmentForClass(item.c.id); return <tr key={item.c.id}><td><button className={analyticsStyles.linkButton} onClick={() => setSelectedClass(item.c.id)}><strong>{item.c.name}</strong></button></td><td>{state.students.filter(student => student.classId === item.c.id && student.status === "ACTIVE").length}</td><td>{pct(item.rate)}</td><td>{item.sessions.length}</td><td>{assignment && <button className={analyticsStyles.messageButton} onClick={() => messageTeacher(assignment.teacherId, { type: "ANALYTICS_SNAPSHOT", entityId: `class-${item.c.id}-${dates[0]}`, label: `${item.c.name} · ${pct(item.rate)} attendance`, contextType: "CLASS_ATTENDANCE", teacherId: assignment.teacherId, classId: item.c.id, subjectId: assignment.subjectId, metrics: { attendance: item.rate ?? 0 } }, `Please review ${item.c.name} attendance.`)}><Send />{sent.startsWith("class-") ? "Sent" : "Message Teacher"}</button>}</td></tr>; })}</tbody></table></section>
      <section className={`${analyticsStyles.panel} ${analyticsStyles.wide}`}><div className={analyticsStyles.heading}><span>Students needing attention</span><small>Attendance evidence only</small></div>{data.studentStats.length ? <table className={analyticsStyles.table}><thead><tr><th>Student</th><th>Class</th><th>Attendance</th><th>Absent</th><th>Late</th><th>Action</th></tr></thead><tbody>{data.studentStats.slice(0, 8).map(item => { const assignment = assignmentForClass(item.student.classId); return <tr key={item.student.id}><td><strong>{item.student.fullName}</strong><small>{item.student.studentId}</small></td><td>{state.classes.find(candidate => candidate.id === item.student.classId)?.name}</td><td>{pct(item.rate)}</td><td>{item.absent}</td><td>{item.late}</td><td>{assignment && <button className={analyticsStyles.messageButton} onClick={() => messageTeacher(assignment.teacherId, { type: "ANALYTICS_SNAPSHOT", entityId: `student-${item.student.id}-${dates[0]}`, label: `${item.student.fullName} · ${pct(item.rate)} attendance`, contextType: "STUDENT_ATTENDANCE", teacherId: assignment.teacherId, classId: item.student.classId, studentId: item.student.id, metrics: { attendance: item.rate ?? 0, absent: item.absent, late: item.late } }, `Please review ${item.student.fullName}'s attendance.`)}><Send /> Message Teacher</button>}</td></tr>; })}</tbody></table> : <Empty />}</section>
      <section className={analyticsStyles.panel}><div className={analyticsStyles.heading}><span>Teacher register activity</span></div>{data.teacherStats.length ? data.teacherStats.map(item => <div className={analyticsStyles.teacher} key={item.teacher.id}><strong>{item.teacher.fullName}</strong><span>{item.submitted}/{item.sessions} submitted · {item.pending} pending</span></div>) : <Empty />}</section>
      <section className={analyticsStyles.panel}><div className={analyticsStyles.heading}><span>Needs attention</span></div>{data.teacherStats.filter(item => item.pending > 0).map(item => { const assignment = state.assignments.find(candidate => candidate.teacherId === item.teacher.id); return <div className={analyticsStyles.attentionItem} key={item.teacher.id}><p><strong>Missing register</strong><br />{assignment && state.classes.find(candidate => candidate.id === assignment.classId)?.name} · {item.pending} pending</p>{assignment && <button className={analyticsStyles.messageButton} onClick={() => messageTeacher(item.teacher.id, { type: "ANALYTICS_SNAPSHOT", entityId: `missing-${item.teacher.id}-${dates[0]}`, label: `${state.classes.find(candidate => candidate.id === assignment.classId)?.name} · Missing register`, contextType: "MISSING_REGISTER", teacherId: item.teacher.id, classId: assignment.classId, subjectId: assignment.subjectId, date: dates.at(-1) }, "Please review this attendance register." )}><Send /> Message Teacher</button>}</div>; })}</section>
    </div>{selectedClass && <ClassDrilldown classId={selectedClass} data={data} state={state} onClose={() => setSelectedClass(null)} />}</div>;
}
function Metric({ label, value, note, icon }: { label: string; value: string | number; note: string; icon: React.ReactNode }) { return <article className={analyticsStyles.metric}><div><span>{label}</span>{icon}</div><strong>{value}</strong><small>{note}</small></article>; }
function Empty() { return <div className={analyticsStyles.empty}><strong>No attendance data yet</strong><span>Analytics will appear once class registers are submitted.</span></div>; }
function ClassDrilldown({ classId, data, state, onClose }: { classId: string; data: ReturnType<typeof buildAnalytics>; state: ReturnType<typeof useXaadirData>["state"]; onClose: () => void }) { const dialog = useDialog(true, onClose); const item = data.classStats.find(candidate => candidate.c.id === classId); if (!item) return null; return <div className={analyticsStyles.overlay} onClick={onClose}><aside ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Class analytics" className={analyticsStyles.drilldown} onClick={event => event.stopPropagation()}><button className={analyticsStyles.close} aria-label="Close class analytics" onClick={onClose}>×</button><span>Class analytics</span><h2>{item.c.name}</h2><p>{state.students.filter(student => student.classId === classId && student.status === "ACTIVE").length} active students</p><div className={analyticsStyles.drillStats}><strong>{pct(item.rate)}</strong><span>Attendance</span><strong>{item.sessions.length}</strong><span>Registers submitted</span></div></aside></div>; }
