import type { MonthlyReport } from "../reports";

const MM = 72 / 25.4;
const MARGIN_X = 15 * MM;
const CONTENT_WIDTH = 180 * MM;
const PAGE_BOTTOM = 25 * MM;
const GREEN: [number, number, number] = [15, 107, 70];
const INK: [number, number, number] = [32, 38, 34];
const MUTED: [number, number, number] = [92, 101, 95];
const RULE: [number, number, number] = [202, 215, 207];
const PALE: [number, number, number] = [247, 250, 248];
const COL_WIDTHS = [8, 18, 47, 16, 15, 12, 16, 22, 26].map((v) => v * MM);
const HEADERS = ["No.", "Student ID", "Student Name", "Present", "Absent", "Late", "Excused", "Attendance", "Status"];

function periodLabel(value: string) { const [year, month] = value.split("-").map(Number); if (!year || !month) return value; return new Intl.DateTimeFormat("en", { month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(Date.UTC(year, month - 1, 1))); }
function classCode(name: string) { return name.replace(/^Grade\s*/i, "").replace(/[^A-Za-z0-9]+/g, "-").replace(/^-|-$/g, "").toUpperCase() || "CLASS"; }
function statusFor(rate: number) { return rate >= 95 ? "Excellent" : rate >= 85 ? "Good" : rate >= 75 ? "Satisfactory" : "Needs Attention"; }
function percentage(value: number) { return `${Number.isInteger(value) ? value.toFixed(0) : value.toFixed(1)}%`; }
function timestamp(date: Date) { const day = date.toLocaleDateString("en-GB", { day: "2-digit", month: "short", timeZone: "UTC" }); const time = date.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true, timeZone: "UTC" }); return `${day} ${date.getUTCFullYear()} · ${time}`; }

// The mark mirrors the Xaadir vector symbol used by the application.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
function drawMark(pdf: any, cx: number, cy: number, size = 30) { const r = size / 2; pdf.setDrawColor(...GREEN); pdf.setLineWidth(2.4); pdf.circle(cx, cy, r); pdf.setLineCap(1); pdf.setLineJoin(1); pdf.setLineWidth(3); pdf.line(cx - r * 0.48, cy - r * 0.48, cx, cy); pdf.line(cx, cy, cx + r * 0.48, cy - r * 0.48); pdf.line(cx - r * 0.48, cy + r * 0.48, cx, cy); pdf.line(cx, cy, cx + r * 0.28, cy + r * 0.29); pdf.setFillColor(...GREEN); pdf.circle(cx + r * 0.54, cy + r * 0.54, r * 0.25, "F"); pdf.setDrawColor(255, 255, 255); pdf.setLineWidth(0.9); pdf.line(cx + r * 0.43, cy + r * 0.54, cx + r * 0.51, cy + r * 0.62); pdf.line(cx + r * 0.51, cy + r * 0.62, cx + r * 0.7, cy + r * 0.42); }

export function renderMonthlyAttendancePdf(report: MonthlyReport, generatedAt = new Date()) {
  return import("jspdf").then(({ jsPDF }) => {
    const pdf = new jsPDF({ unit: "pt", format: "a4" }); const W = pdf.internal.pageSize.getWidth(); const H = pdf.internal.pageSize.getHeight();
    const period = periodLabel(report.month); const school = report.school?.name ?? ""; const generated = timestamp(generatedAt); const reference = `XDR-ATT-${classCode(report.schoolClass.name)}-${report.month}`;
    const line = (y: number, color = RULE, width = 0.55) => { pdf.setDrawColor(...color); pdf.setLineWidth(width); pdf.line(MARGIN_X, y, W - MARGIN_X, y); };
    const footer = (page: number, total: number) => { line(H - 39); pdf.setFont("times", "normal"); pdf.setFontSize(7.3); pdf.setTextColor(...MUTED); pdf.text(reference, MARGIN_X, H - 23); pdf.text(`${report.schoolClass.name} · ${period}`, W / 2, H - 23, { align: "center" }); pdf.text(`Page ${page} of ${total}`, W - MARGIN_X, H - 23, { align: "right" }); };
    const runningHeader = () => { pdf.setFont("times", "bold"); pdf.setFontSize(10); pdf.setTextColor(...GREEN); pdf.text("Xaadir", MARGIN_X, 27); pdf.setFont("times", "normal"); pdf.setFontSize(9); pdf.setTextColor(...MUTED); pdf.text(`Monthly Attendance Report  ·  ${report.schoolClass.name} · ${period}`, MARGIN_X + 38, 27); line(37, GREEN, 0.7); return 54; };
    const fullHeader = () => { const top = 35; drawMark(pdf, MARGIN_X + 15, top + 18, 30); pdf.setFont("times", "bold"); pdf.setFontSize(16); pdf.setTextColor(...GREEN); pdf.text("Xaadir", MARGIN_X + 38, top + 15); pdf.setFont("times", "bold"); pdf.setFontSize(8); pdf.setTextColor(...MUTED); if (school) pdf.text(school.toUpperCase(), MARGIN_X + 38, top + 28); pdf.setFont("times", "normal"); pdf.setFontSize(8); pdf.setTextColor(...MUTED); pdf.text("SCHOOL ATTENDANCE SYSTEM", MARGIN_X + 38, top + (school ? 40 : 28)); pdf.setFont("times", "bold"); pdf.setFontSize(18); pdf.setTextColor(...INK); pdf.text("MONTHLY", W - MARGIN_X, top + 14, { align: "right" }); pdf.text("ATTENDANCE REPORT", W - MARGIN_X, top + 33, { align: "right" }); pdf.setFont("times", "normal"); pdf.setFontSize(11); pdf.setTextColor(...MUTED); pdf.text(period, W - MARGIN_X, top + 49, { align: "right" }); line(top + 68, GREEN, 0.85); return top + 92; };
    const tableHeader = (y: number) => { pdf.setFillColor(...PALE); pdf.rect(MARGIN_X, y, CONTENT_WIDTH, 22, "F"); line(y + 22, RULE, 0.65); let x = MARGIN_X; pdf.setFont("times", "bold"); pdf.setFontSize(7.5); pdf.setTextColor(...GREEN); HEADERS.forEach((h, i) => { const centered = i === 0 || (i >= 3 && i <= 7); pdf.text(h, x + (centered ? COL_WIDTHS[i] / 2 : 3), y + 14, { align: centered ? "center" : "left" }); x += COL_WIDTHS[i]; }); return y + 22; };
    let y = fullHeader(); pdf.setFont("times", "bold"); pdf.setFontSize(10); pdf.setTextColor(...GREEN); pdf.text("REPORT DETAILS", MARGIN_X, y); y += 15;
    const mid = MARGIN_X + CONTENT_WIDTH / 2; pdf.setDrawColor(...RULE); pdf.setLineWidth(0.45); pdf.line(mid, y, mid, y + 67); const left = [["Teacher", report.teacher.fullName], ["Teacher ID", report.teacher.employeeId], ["Class", report.schoolClass.name], ["Subject", report.subject.name]]; const right = [["Students", String(report.students.length)], ["Sessions Held", String(report.sessionCount)], ["Report Ref", reference], ["Generated", generated]];
    const drawDetails = (items: string[][], x: number) => items.forEach(([label, value], i) => { const yy = y + i * 17; pdf.setFont("times", "bold"); pdf.setFontSize(7.5); pdf.setTextColor(...MUTED); pdf.text(label.toUpperCase(), x, yy); pdf.setFont("times", "normal"); pdf.setFontSize(9); pdf.setTextColor(...INK); pdf.text(value, x, yy + 10, { maxWidth: CONTENT_WIDTH / 2 - 18 }); }); drawDetails(left, MARGIN_X); drawDetails(right, mid + 12); y += 82;
    pdf.setFont("times", "bold"); pdf.setFontSize(10); pdf.setTextColor(...GREEN); pdf.text("ATTENDANCE OVERVIEW", MARGIN_X, y); y += 10; const metrics = [["PRESENT", report.totals.PRESENT], ["ABSENT", report.totals.ABSENT], ["LATE", report.totals.LATE], ["EXCUSED", report.totals.EXCUSED], ["ATTENDANCE", percentage(report.averageAttendance)]]; const sw = CONTENT_WIDTH / metrics.length; pdf.setFillColor(...PALE); pdf.rect(MARGIN_X, y, CONTENT_WIDTH, 43, "F"); line(y, RULE); line(y + 43, RULE); metrics.forEach(([label, value], i) => { const x = MARGIN_X + i * sw; if (i > 0) { pdf.setDrawColor(...RULE); pdf.setLineWidth(0.45); pdf.line(x, y + 8, x, y + 35); } pdf.setFont("times", "bold"); pdf.setFontSize(7.5); pdf.setTextColor(...GREEN); pdf.text(String(label), x + sw / 2, y + 15, { align: "center" }); pdf.setFontSize(13); pdf.setTextColor(...INK); pdf.text(String(value), x + sw / 2, y + 33, { align: "center" }); }); y += 65;
    pdf.setFont("times", "bold"); pdf.setFontSize(11.5); pdf.setTextColor(...INK); pdf.text("STUDENT ATTENDANCE REGISTER", MARGIN_X, y); pdf.setFont("times", "normal"); pdf.setFontSize(9); pdf.setTextColor(...MUTED); pdf.text(`${report.schoolClass.name} · ${report.subject.name} · ${period}`, MARGIN_X, y + 14); y += 26; y = tableHeader(y);
    const sorted = [...report.studentRows].sort((a, b) => a.fullName.localeCompare(b.fullName)); sorted.forEach((student, index) => { const nameLines = pdf.splitTextToSize(student.fullName, COL_WIDTHS[2] - 8); const statusLines = pdf.splitTextToSize(statusFor(student.rate), COL_WIDTHS[8] - 8); const lines = Math.max(nameLines.length, statusLines.length); const rowH = Math.max(21, lines * 10 + 7); if (y + rowH > H - PAGE_BOTTOM) { pdf.addPage(); y = runningHeader(); y = tableHeader(y); } if (index % 2 === 1) { pdf.setFillColor(251, 252, 251); pdf.rect(MARGIN_X, y, CONTENT_WIDTH, rowH, "F"); } let x = MARGIN_X; const vals: (string | string[])[] = [String(index + 1).padStart(2, "0"), student.studentId, nameLines, String(student.counts.PRESENT), String(student.counts.ABSENT), String(student.counts.LATE), String(student.counts.EXCUSED), percentage(student.rate), statusLines]; vals.forEach((value, i) => { const centered = i === 0 || (i >= 3 && i <= 7); pdf.setFont("times", i === 2 ? "bold" : "normal"); pdf.setFontSize(8.5); pdf.setTextColor(...INK); const arr = Array.isArray(value) ? value : [value]; arr.forEach((part, li) => pdf.text(String(part), x + (centered ? COL_WIDTHS[i] / 2 : 4), y + 14 + li * 10, { align: centered ? "center" : "left" })); x += COL_WIDTHS[i]; }); line(y + rowH, RULE, 0.4); y += rowH; });
    const total = pdf.getNumberOfPages(); for (let page = 1; page <= total; page += 1) { pdf.setPage(page); footer(page, total); } return pdf;
  });
}
