"use client";

import { Check, ChevronLeft, Search, Send } from "lucide-react";
import { useMemo, useState } from "react";
import type { AttendanceStatus } from "@/lib/models";
import { datesForSchoolWeek, formatSchoolDate, shortWeekday } from "@/lib/schoolCalendar";
import type { TeacherClassSummary } from "./types";
import styles from "./teacher.module.css";

const statuses: AttendanceStatus[] = ["PRESENT", "ABSENT", "LATE", "EXCUSED"];
type Marks = Record<string, AttendanceStatus | null>;
interface AttendanceFlowProps { classSummary: TeacherClassSummary; teacherName: string; timeLabel: string; date: string; weekRecords?: Record<string, Record<string, AttendanceStatus>>; onDateChange?: (date: string) => void; initialRecords?: Array<{ studentId: string; status: AttendanceStatus }>; submittedAt?: string; onBack?: () => void; onSaveDraft: (records: Array<{ studentId: string; status: AttendanceStatus }>) => void; onSubmit: (records: Array<{ studentId: string; status: AttendanceStatus }>) => void | Promise<void>; }

export function AttendanceFlow({ classSummary, teacherName, timeLabel, date, weekRecords = {}, onDateChange, initialRecords = [], submittedAt, onBack, onSaveDraft, onSubmit }: AttendanceFlowProps) {
  const [marks, setMarks] = useState<Marks>(() => { let draft = initialRecords; try { const raw = typeof window !== "undefined" ? localStorage.getItem(`xaadir-draft-${classSummary.schoolClass.id}-${date}`) : null; if (!initialRecords.length && raw) draft = JSON.parse(raw); } catch { /* storage unavailable */ } return Object.fromEntries(classSummary.students.map((student) => [student.id, draft.find((record) => record.studentId === student.id)?.status ?? null])); });
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<AttendanceStatus | "ALL" | "UNMARKED">("ALL"); const [confirming, setConfirming] = useState(false); const [editing, setEditing] = useState(!submittedAt); const [saved, setSaved] = useState(false); const [error, setError] = useState("");
  const totals = useMemo(() => classSummary.students.reduce<Record<string, number>>((a, student) => { const status = marks[student.id]; a[status ?? "UNMARKED"] += 1; return a; }, { PRESENT: 0, ABSENT: 0, LATE: 0, EXCUSED: 0, UNMARKED: 0 }), [classSummary.students, marks]);
  const visible = classSummary.students.filter((student) => student.fullName.toLowerCase().includes(query.toLowerCase()) || student.studentId.toLowerCase().includes(query.toLowerCase())).filter((student) => filter === "ALL" || (filter === "UNMARKED" ? !marks[student.id] : marks[student.id] === filter));
  const payload = () => Object.entries(marks).flatMap(([studentId, status]) => status ? [{ studentId, status }] : []);
  function markAll() { setMarks((current) => Object.fromEntries(classSummary.students.map((student) => [student.id, current[student.id] ?? "PRESENT"]))); setSaved(false); }
  function setStatus(id: string, status: AttendanceStatus) { setMarks((current) => ({ ...current, [id]: status })); setSaved(false); }
  async function submit() { if (totals.UNMARKED) { setError(`${totals.UNMARKED} student${totals.UNMARKED === 1 ? " has" : "s have"} not been marked.`); return; } setError(""); await onSubmit(payload()); setConfirming(false); setEditing(false); }
  if (submittedAt && !editing) return <div className={styles.attendancePage}><button className={styles.backButton} onClick={onBack}><ChevronLeft /> Back to attendance</button><section className={`${styles.panel} ${styles.successPanel}`} role="status"><span className={styles.successMark}><Check /></span><span className={styles.eyebrow}>Attendance recorded</span><h1>{classSummary.schoolClass.name}</h1><p>{totals.PRESENT} Present · {totals.ABSENT} Absent · {totals.LATE} Late · {totals.EXCUSED} Excused</p><button className={styles.secondaryButton} onClick={() => setEditing(true)}>Edit Attendance</button></section></div>;
  return <div className={styles.attendancePage} onKeyDown={(event) => { if (!editing || (event.target as HTMLElement).tagName === "INPUT") return; const id = (event.target as HTMLElement).closest("[data-student-id]")?.getAttribute("data-student-id"); const student = classSummary.students.find((item) => item.id === id); const keyMap: Record<string, AttendanceStatus> = { p: "PRESENT", a: "ABSENT", l: "LATE", e: "EXCUSED" }; if (student && keyMap[event.key.toLowerCase()]) setStatus(student.id, keyMap[event.key.toLowerCase()]); }} tabIndex={0}>
    <header className={styles.attendanceHeader}><div className={styles.attendanceHeading}>{onBack && <button className={styles.backButton} onClick={onBack}><ChevronLeft /> Back to My Classes</button>}<span className={styles.eyebrow}>Daily student attendance</span><h1>{classSummary.schoolClass.name}</h1><p>{classSummary.subject.name} · {formatSchoolDate(date)} · {timeLabel}</p><small className={styles.registerMeta}>Teacher: {teacherName} · {classSummary.students.length} Students</small></div><button className={styles.secondaryButton} onClick={markAll} disabled={!editing}>Mark All Present</button></header>
    <nav className={styles.schoolWeekStrip} aria-label="Attendance school week">{datesForSchoolWeek(date).map((day) => <button key={day} className={day === date ? styles.selectedDay : ""} onClick={() => onDateChange?.(day)}><span>{shortWeekday(day)}</span><strong>{day.slice(-2)}</strong>{weekRecords[day] && <small>✓</small>}</button>)}</nav>
    <section className={styles.registerToolbar}><div className={styles.registerSearch}><Search /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search student or ID..." aria-label="Search students" /></div><div className={styles.filterBar}>{(["ALL", ...statuses, "UNMARKED"] as const).map((item) => <button key={item} className={filter === item ? styles.activeFilter : ""} onClick={() => setFilter(item)}>{item === "ALL" ? `All ${classSummary.students.length}` : `${item === "UNMARKED" ? "Unmarked" : item.charAt(0) + item.slice(1).toLowerCase()} ${totals[item]}`}</button>)}</div></section>
    <section className={styles.attendanceTotals} aria-label="Live attendance totals">{[...statuses, "UNMARKED" as const].map((status) => <span key={status} data-status={status.toLowerCase()}><strong>{totals[status]}</strong>{status === "UNMARKED" ? "Unmarked" : status.charAt(0) + status.slice(1).toLowerCase()}</span>)}</section>
    <section className={styles.register} aria-label={`${classSummary.schoolClass.name} attendance register`}><div className={styles.registerHeader}><span>No.</span><span>Student</span><span>Status</span></div>{visible.map((student) => <div className={styles.attendanceRow} key={student.id}><span className={styles.rowNumber}>{String(classSummary.students.indexOf(student) + 1).padStart(2, "0")}</span><div className={styles.studentIdentity}><strong>{student.fullName}</strong><small>{student.studentId}</small></div><div className={styles.segmented} role="radiogroup" aria-label={`Attendance status for ${student.fullName}`}>{statuses.map((status) => <button key={status} type="button" role="radio" disabled={!editing} aria-checked={marks[student.id] === status} data-status={status.toLowerCase()} onClick={() => setStatus(student.id, status)}>{status.charAt(0) + status.slice(1).toLowerCase()}</button>)}</div></div>)}</section>
    <footer className={styles.stickySubmit}><p><strong>{totals.PRESENT} Present · {totals.ABSENT} Absent · {totals.LATE} Late · {totals.EXCUSED} Excused · {totals.UNMARKED} Unmarked</strong><span>{saved ? "✓ Saved" : "Keyboard: P, A, L, E"}</span></p>{editing && <><button className={styles.secondaryButton} onClick={() => { onSaveDraft(payload()); try { localStorage.setItem(`xaadir-draft-${classSummary.schoolClass.id}-${date}`, JSON.stringify(payload())); } catch { /* storage unavailable */ } setSaved(true); }}>Save Draft</button><button className={styles.primaryButton} onClick={() => setConfirming(true)}><Send /> Submit Attendance</button></>}</footer>
    {error && <p className={styles.submitError} role="alert">{error} <button onClick={() => setFilter("UNMARKED")}>View Unmarked</button></p>}
    {confirming && <div className={styles.modalBackdrop}><section className={styles.confirmDialog} role="dialog" aria-modal="true"><span className={styles.dialogIcon}><Check /></span><h2>Submit {classSummary.schoolClass.name} attendance?</h2><p>{formatSchoolDate(date)}<br />{classSummary.students.length} students<br /><br />Present: {totals.PRESENT} · Absent: {totals.ABSENT} · Late: {totals.LATE} · Excused: {totals.EXCUSED}</p><div><button className={styles.secondaryButton} onClick={() => setConfirming(false)}>Cancel</button><button className={styles.primaryButton} onClick={submit}>Submit Attendance</button></div></section></div>}
    <section className={`${styles.panel} ${styles.weeklyRegister}`}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Weekly register</span><h2>Read-only class overview</h2></div><span className={styles.registerMeta}>P Present · A Absent · L Late · E Excused</span></div><div className={styles.weeklyRows}><div className={styles.weeklyRow}><strong>Student</strong>{datesForSchoolWeek(date).map((day) => <button key={day} onClick={() => onDateChange?.(day)}>{shortWeekday(day)} {day.slice(-2)}</button>)}</div>{classSummary.students.map((student) => <div className={styles.weeklyRow} key={student.id}><span>{student.fullName}</span>{datesForSchoolWeek(date).map((day) => { const status = weekRecords[day]?.[student.id]; return <button key={day} title={`${formatSchoolDate(day)}: ${status ?? "Unmarked"}`} onClick={() => onDateChange?.(day)}>{status ? status[0] : "—"}</button>; })}</div>)}</div></section>
  </div>;
}
