"use client";
import { FileSpreadsheet, FileText, RefreshCw } from "lucide-react";
import { useState } from "react";
import { useXaadirData } from "@/components/providers";
import { generateMonthlyClassReport } from "@/lib/reports";
import { renderMonthlyAttendancePdf } from "@/lib/reports/pdfTemplate";
import styles from "./teacher.module.css";
const monthLabel=(m:string)=>new Intl.DateTimeFormat("en",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(`${m}-01T00:00:00Z`));
export function TeacherReports({teacherId}:{teacherId:string}){const {state}=useXaadirData();const teacher=state.teachers.find(t=>t.id===teacherId);const assignments=state.assignments.filter(a=>a.teacherId===teacherId);const [month,setMonth]=useState("2026-09");const [classId,setClassId]=useState(assignments[0]?.classId??"");const assignment=assignments.find(a=>a.classId===classId)||assignments[0];const schoolClass=assignment&&state.classes.find(c=>c.id===assignment.classId);const subject=assignment&&state.subjects.find(s=>s.id===assignment.subjectId);if(!teacher||!schoolClass||!subject)return null;const report=generateMonthlyClassReport({teacher,schoolClass,subject,students:state.students.filter(s=>s.classId===schoolClass.id&&s.status==="ACTIVE").sort((a,b)=>a.fullName.localeCompare(b.fullName)),sessions:state.attendanceSessions.filter(s=>s.classId===schoolClass.id&&s.teacherId===teacherId&&s.date.startsWith(month)),records:state.attendanceRecords,month});
 const pdf=()=>void renderMonthlyAttendancePdf(report).then(p=>p.save(`Xaadir_${schoolClass.name.replace(/\s+/g,"-")}_Monthly-Attendance_${monthLabel(month).replace(/\s+/g,"-")}.pdf`));
 const excel=()=>void import("xlsx").then(X=>{const wb=X.utils.book_new();X.utils.book_append_sheet(wb,X.utils.aoa_to_sheet([["XAADIR MONTHLY ATTENDANCE REPORT"],["School",state.school.name],["Teacher",teacher.fullName],["Teacher ID",teacher.employeeId],["Class",schoolClass.name],["Subject",subject.name],["Month",monthLabel(month)],["Students",report.students.length],["Sessions Held",report.sessionCount],["Average Attendance",`${report.averageAttendance.toFixed(1)}%`]]),"Monthly Summary");X.utils.book_append_sheet(wb,X.utils.json_to_sheet(report.studentRows.map((s,i)=>({No:i+1,"Student ID":s.studentId,"Student Name":s.fullName,Present:s.counts.PRESENT,Absent:s.counts.ABSENT,Late:s.counts.LATE,Excused:s.counts.EXCUSED,"Attendance %":`${s.rate.toFixed(1)}%`,Status:s.rate>=95?"Excellent":s.rate>=85?"Good":s.rate>=75?"Satisfactory":"Needs Attention"}))),"Student Attendance");X.utils.book_append_sheet(wb,X.utils.json_to_sheet(report.sessions.map(s=>({Date:s.date,Subject:subject.name,"Scheduled Time":state.scheduleSessions.find(x=>x.id===s.scheduleSessionId)?.startTime??""}))),"Session Breakdown");X.writeFile(wb,`Xaadir_${schoolClass.name.replace(/\s+/g,"-")}_Monthly-Attendance_${monthLabel(month).replace(/\s+/g,"-")}.xlsx`)});
 return <div className={styles.pageStack}><header className={styles.pageHeader}><div><span className={styles.eyebrow}>Teacher workspace</span><h1>Monthly Reports</h1><p>Review and export monthly attendance reports for your assigned classes.</p></div><div className={styles.reportControls}><select value={month} onChange={e=>setMonth(e.target.value)} aria-label="Month"><option value="2026-09">September 2026</option><option value="2026-08">August 2026</option></select><select value={schoolClass.id} onChange={e=>setClassId(e.target.value)} aria-label="Class">{assignments.map(a=><option key={a.classId} value={a.classId}>{state.classes.find(c=>c.id===a.classId)?.name}</option>)}</select></div></header><section className={styles.reportHero}><div><span className={styles.eyebrow}>Attendance report</span><h2>{schoolClass.name}</h2><p>{subject.name} · {monthLabel(month)} · {teacher.fullName}</p></div><div className={styles.reportActions}><button className={styles.secondaryButton} onClick={pdf}><FileText/> Download PDF</button><button className={styles.primaryButton} onClick={excel}><FileSpreadsheet/> Download Excel</button></div></section><section className={styles.reportMetrics}>{[["Students",report.students.length],["Sessions",report.sessionCount],["Average",`${report.averageAttendance.toFixed(1)}%`],["Present",report.totals.PRESENT],["Absent",report.totals.ABSENT],["Late",report.totals.LATE],["Excused",report.totals.EXCUSED]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</section><section className={`${styles.panel} ${styles.reportTable}`}><div className={styles.panelHeading}><div><span className={styles.eyebrow}>Student attendance</span><h2>Monthly register</h2></div><RefreshCw/></div>{report.sessionCount===0?<p className={styles.emptyCopy}>No attendance records were found for this class and month.</p>:<div className={styles.reportRows}><table><thead><tr>{["No.","Student ID","Student Name","Present","Absent","Late","Excused","Attendance %","Status"].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{report.studentRows.map((s,i)=><tr key={s.id}><td>{String(i+1).padStart(2,"0")}</td><td>{s.studentId}</td><th scope="row">{s.fullName}</th><td>{s.counts.PRESENT}</td><td>{s.counts.ABSENT}</td><td>{s.counts.LATE}</td><td>{s.counts.EXCUSED}</td><td>{s.rate.toFixed(1)}%</td><td><em>{s.rate>=95?"Excellent":s.rate>=85?"Good":s.rate>=75?"Satisfactory":"Needs Attention"}</em></td></tr>)}</tbody></table></div>}</section></div>;
}
