"use client";

import { AlertCircle, ArrowRight, CalendarCheck, Check, ChevronLeft, ChevronRight, Clock3 } from "lucide-react";
import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { useXaadirData } from "@/components/providers";
import type { ScheduleSession } from "@/lib/models";
import { datesForSchoolWeek, formatSchoolDate, isSchoolDay, shiftSchoolDay, shortWeekday, weekdayForDate } from "@/lib/schoolCalendar";
import { AttendanceFlow } from "./AttendanceFlow";
import { TeacherAttendanceHistory } from "./TeacherAttendanceHistory";
import { TeacherClasses, PageIntro } from "./TeacherClasses";
import { TeacherDashboard } from "./TeacherDashboard";
import { TeacherHelp } from "./TeacherHelp";
import { TeacherProfile } from "./TeacherProfile";
import { TeacherReports } from "./TeacherReports";
import { TeacherSchedule } from "./TeacherSchedule";
import type { TeacherClassSummary, TeacherSection, TeacherViewModel } from "./types";
import styles from "./teacher.module.css";

const today = () => new Date().toISOString().slice(0, 10);

export function TeacherSystem({ section, classId }: { section: TeacherSection; classId?: string }) {
  const router = useRouter();
  const { state, actor, submitAttendance, workSession, checkInWork, checkOutWork } = useXaadirData();
  const [selectedDate, setSelectedDate] = useState(today); const [selectedSessionId, setSelectedSessionId] = useState<string | null>(null); const [error, setError] = useState("");
  const teacherId = actor.teacherId ?? state.users.find((user) => user.role === "TEACHER")?.teacherId;
  const model = useMemo<TeacherViewModel | null>(() => { const teacher = state.teachers.find((item) => item.id === teacherId); if (!teacher) return null; const assignments = state.assignments.filter((a) => a.teacherId === teacher.id); const classes = assignments.reduce<TeacherClassSummary[]>((items, assignment) => { const schoolClass = state.classes.find((c) => c.id === assignment.classId); const subject = state.subjects.find((s) => s.id === assignment.subjectId); if (!schoolClass || !subject) return items; items.push({ schoolClass, subject, students: state.students.filter((s) => s.classId === schoolClass.id && s.status === "ACTIVE"), nextSession: state.scheduleSessions.find((s) => s.teacherId === teacher.id && s.classId === schoolClass.id && s.subjectId === subject.id) }); return items; }, []); const checkIns = state.teacherCheckIns.filter((item) => item.teacherId === teacher.id).map((item) => { const session = state.scheduleSessions.find((candidate) => candidate.id === item.scheduleSessionId); return { ...item, session, schoolClass: state.classes.find((c) => c.id === session?.classId), subject: state.subjects.find((s) => s.id === session?.subjectId) }; }); return { teacher, classes, todaySessions: state.scheduleSessions.filter((s) => s.teacherId === teacher.id), checkIns }; }, [state, teacherId]);
  if (!model) return <EmptyTeacher />;
  const activeSession = state.scheduleSessions.find((session) => session.id === selectedSessionId); const requestedClass = classId ? model.classes.find((item) => item.schoolClass.id === classId) : undefined; const currentClass = model.classes.find((item) => item.schoolClass.id === activeSession?.classId && item.subject.id === activeSession?.subjectId) ?? requestedClass;
  const sessionFor = (item: TeacherClassSummary) => state.scheduleSessions.find((s) => s.teacherId === model.teacher.id && s.classId === item.schoolClass.id && s.subjectId === item.subject.id && s.day === weekdayForDate(selectedDate));
  const startAttendance = (item: TeacherClassSummary) => { if (selectedDate > today()) { setError("This school day is upcoming. Attendance can be submitted on the day."); return; } const session = sessionFor(item); if (session) setSelectedSessionId(session.id); else setError("No class is scheduled for this school day."); };
  const selectedClassSession = activeSession ?? (currentClass ? sessionFor(currentClass) : undefined);
  const existing = selectedClassSession && state.attendanceSessions.find((s) => s.scheduleSessionId === selectedClassSession.id && s.date === selectedDate);
  if (currentClass && (activeSession || classId)) { const session = activeSession ?? currentClass.nextSession; if (!session) return <section className={styles.panel}><button className={styles.backButton} onClick={() => router.push("/teacher/classes")}><ChevronLeft /> Back to My Classes</button><h1>{currentClass.schoolClass.name}</h1><p>No attendance session is configured for this class.</p></section>; const weekRecords = Object.fromEntries(datesForSchoolWeek(selectedDate).map((day) => { const daySession = state.scheduleSessions.find((item) => item.teacherId === model.teacher.id && item.classId === currentClass.schoolClass.id && item.subjectId === currentClass.subject.id && item.day === weekdayForDate(day)); const dayAttendance = daySession && state.attendanceSessions.find((item) => item.scheduleSessionId === daySession.id && item.date === day); return [day, dayAttendance ? Object.fromEntries(state.attendanceRecords.filter((record) => record.attendanceSessionId === dayAttendance.id).map((record) => [record.studentId, record.status])) : {}]; })); const records = existing ? state.attendanceRecords.filter((r) => r.attendanceSessionId === existing.id).map((r) => ({ studentId: r.studentId, status: r.status })) : []; return <AttendanceFlow key={selectedDate} classSummary={currentClass} teacherName={model.teacher.fullName} timeLabel={`${session.startTime}–${session.endTime}`} date={selectedDate} weekRecords={weekRecords} onDateChange={setSelectedDate} initialRecords={records} submittedAt={existing?.submittedAt} onBack={() => router.push("/teacher/classes")} onSaveDraft={(draft) => { try { localStorage.setItem(`xaadir-draft-${currentClass.schoolClass.id}-${selectedDate}`, JSON.stringify(draft)); } catch { /* storage unavailable */ } }} onSubmit={async (recordsToSave) => { const result = submitAttendance({ scheduleSessionId: session.id, date: selectedDate, records: recordsToSave }); if (!result.ok) { setError(result.error); throw new Error(result.error); } setError(""); }} />; }
  const isClosed = !isSchoolDay(selectedDate); const classesToday = model.classes.map((item) => ({ item, session: sessionFor(item) })).filter(({ session }) => session);
  return <>{error.trim() && <div className={styles.errorBanner} role="alert"><AlertCircle />{error}<button onClick={() => setError("")} aria-label="Dismiss">×</button></div>}{section === "dashboard" && <TeacherDashboard model={model} nextSession={classesToday[0]?.session} nextClassName={classesToday[0]?.item.schoolClass.name} nextSubjectName={classesToday[0]?.item.subject.name} nextStudentCount={classesToday[0]?.item.students.length} workSession={workSession} onCheckIn={checkInWork} onCheckOut={checkOutWork} onTakeAttendance={() => classesToday[0] && startAttendance(classesToday[0].item)} />}{section === "classes" && <TeacherClasses classes={model.classes} onOpen={(item) => router.push(`/teacher/classes/${item.schoolClass.id}`)} />}{section === "attendance" && <AttendanceHome classes={classesToday} selectedDate={selectedDate} setDate={setSelectedDate} isClosed={isClosed} onOpen={startAttendance} onToday={() => setSelectedDate(today())} state={state} />}{section === "schedule" && <TeacherSchedule classes={model.classes} />}{section === "my-attendance" && <TeacherAttendanceHistory history={model.checkIns} />}{section === "reports" && <TeacherReports teacherId={model.teacher.id} />}{section === "profile" && <TeacherProfile model={model} />}{section === "help" && <TeacherHelp />}</>;
}

function AttendanceHome({ classes, selectedDate, setDate, isClosed, onOpen, onToday, state }: { classes: Array<{ item: TeacherClassSummary; session?: ScheduleSession }>; selectedDate: string; setDate: (date: string) => void; isClosed: boolean; onOpen: (item: TeacherClassSummary) => void; onToday: () => void; state: ReturnType<typeof useXaadirData>["state"] }) {
  const week = datesForSchoolWeek(selectedDate); const completed = classes.filter(({ session }) => state.attendanceSessions.some((a) => a.scheduleSessionId === session?.id && a.date === selectedDate)).length;
  const move = (direction: 1 | -1) => setDate(shiftSchoolDay(selectedDate, direction));
  return <div className={styles.pageStack}><PageIntro title="Attendance" copy="Record and review daily attendance for your assigned classes." /><section className={styles.dateNavigator}><button aria-label="Previous school day" onClick={() => move(-1)}><ChevronLeft /></button><div><strong>{formatSchoolDate(selectedDate)}</strong>{selectedDate === today() && <button onClick={onToday}>Today</button>}</div><button aria-label="Next school day" onClick={() => move(1)}><ChevronRight /></button></section><nav className={styles.schoolWeekStrip} aria-label="School week">{week.map((date) => <button key={date} className={date === selectedDate ? styles.selectedDay : ""} onClick={() => setDate(date)}><span>{shortWeekday(date)}</span><strong>{date.slice(-2)}</strong></button>)}</nav>{isClosed ? <section className={`${styles.panel} ${styles.closedDay}`}><span className={styles.eyebrow}>Closed day</span><h2>No classes scheduled</h2><p>{formatSchoolDate(selectedDate, { weekday: "long" })} is a non-school day for this school.</p></section> : <><section className={styles.dailyProgress}><div><span className={styles.eyebrow}>Today&apos;s attendance</span><strong>{completed} of {classes.length} classes completed</strong></div><div className={styles.progressTrack}><span style={{ width: `${classes.length ? (completed / classes.length) * 100 : 0}%` }} /></div><small>Completed {completed} · Remaining {Math.max(0, classes.length - completed)} · Students {classes.reduce((sum, item) => sum + item.item.students.length, 0)}</small></section><section className={styles.attendanceClassList}>{classes.length ? classes.map(({ item, session }) => { const record = state.attendanceSessions.find((a) => a.scheduleSessionId === session?.id && a.date === selectedDate); return <article className={styles.panel} key={`${item.schoolClass.id}-${item.subject.id}`}><span className={styles.lessonIcon}><CalendarCheck /></span><div><h2>{item.schoolClass.name}</h2><p>{item.subject.name} · {item.students.length} students</p>{session && <small><Clock3 />{session.startTime}–{session.endTime}</small>}</div><span className={record ? styles.readyBadge : styles.waitingBadge}>{record ? <><Check /> Attendance recorded</> : "Not started"}</span><button className={styles.inlineButton} onClick={() => onOpen(item)}>{record ? "View Attendance" : "Open Register"} <ArrowRight /></button></article>; }) : <p className={styles.emptyCopy}>No classes scheduled for this school day.</p>}</section></>}</div>;
}

function EmptyTeacher() { return <section className="panel"><AlertCircle /><h1>Teacher profile unavailable</h1><p>This workspace needs a teacher account linked by an administrator.</p></section>; }
